### ISSUE TITLE
App Crash on the new release 1.27 beta

### ISSUE THREAD

**Issue by rickdtc** [Hamza417/Peristyle#11]
# Steps to reproduce

1. Set blur parameter to any value 
2. Try to slide it back to 0, app crashes 

# Screen recording

https://github.com/Hamza417/Peristyle/assets/74096544/e42e41ec-9e40-48a5-bab2-1d669f343c6e

# Crash log

```
FATAL EXCEPTION: main
Process: app.simple.peri, PID: 7982
java.lang.IllegalArgumentException: nativePtr is null
	at libcore.util.NativeAllocationRegistry.registerNativeAllocation(NativeAllocationRegistry.java:264)
	at android.graphics.RenderEffect.<init>(RenderEffect.java:314)
	at android.graphics.RenderEffect.createBlurEffect(RenderEffect.java:117)
	at app.simple.peri.ui.MainScreen$$ExternalSyntheticApiModelOutline0.m(SourceFile:5)
	at app.simple.peri.ui.WallpaperScreen.setRenderEffectOnWallpaper(Unknown Source:130)
	at app.simple.peri.ui.WallpaperScreen$$ExternalSyntheticLambda7.onValueChange(SourceFile:1)
	at app.simple.peri.ui.WallpaperScreen$$ExternalSyntheticLambda7.onValueChange(SourceFile:10)
	at com.google.android.material.slider.BaseSlider.snapThumbToValue(SourceFile:163)
	at com.google.android.material.slider.BaseSlider.snapTouchPosition(SourceFile:50)
	at com.google.android.material.slider.BaseSlider.onTouchEvent(SourceFile:107)
	at android.view.View.dispatchTouchEvent(View.java:15544)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:1116)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1971)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:1332)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchTouchEvent(SourceFile:3)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:1074)
	at android.view.View.dispatchPointerEvent(View.java:15803)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:8153)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7877)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7213)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7270)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7236)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7434)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7244)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7491)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7217)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7270)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7236)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7244)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7217)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10788)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10676)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10632)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10926)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:285)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:262)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:10874)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:11020)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
	at android.view.Choreographer.doFrame(Choreographer.java:844)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by Hamza417** [comment]
Should be fixed now in the 128 build.
