### ISSUE TITLE
Crash app

### ISSUE THREAD

**Issue by Pazengaz** [Hamza417/Peristyle#2]
Application doesn't start, crashes when opened
Xiaomi redmi note 6 pro
Android 9 
MIUI GLOBAL 12.0.1.0 (PEKMIXM)
3/32GB
Model M1806E7TG

```java
java.lang.RuntimeException: Unable to start activity ComponentInfo{app.simple.peri/app.simple.peri.activities.MainActivity}: java.lang.IllegalArgumentException: Authenticator combination is unsupported on API 28: BIOMETRIC_STRONG | DEVICE_CREDENTIAL
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.lang.IllegalArgumentException: Authenticator combination is unsupported on API 28: BIOMETRIC_STRONG | DEVICE_CREDENTIAL
	at androidx.biometric.t.a(SourceFile:87)
	at app.simple.peri.activities.MainActivity.onCreate(SourceFile:153)
	at android.app.Activity.performCreate(Activity.java:7224)
	at android.app.Activity.performCreate(Activity.java:7213)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
	... 11 more
```

**Comment by Hamza417** [comment]
It should be fixed in the next update, you can run this and let me know.

[app-prod-release.zip](https://github.com/Hamza417/Peristyle/files/13856284/app-prod-release.zip)
